[build]
command = "yarn build"
publish = "dist"

[build.environment]
NETLIFY_USE_YARN = "true"

# studio does all routing client side - rediect everything to the SPA root.
[[redirects]]
from = "/*"
status = 200
to = "/"
